//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppCenter.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AppCenter.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tsdragon0404@gmail.com.
        /// </summary>
        public static string About_Email1 {
            get {
                return ResourceManager.GetString("About_Email1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about.
        /// </summary>
        public static string About_PageTitle {
            get {
                return ResourceManager.GetString("About_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate me.
        /// </summary>
        public static string About_RateMe {
            get {
                return ResourceManager.GetString("About_RateMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for using my app :).
        /// </summary>
        public static string About_ThankYou {
            get {
                return ResourceManager.GetString("About_ThankYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version: 2.0.0.0.
        /// </summary>
        public static string About_Version {
            get {
                return ResourceManager.GetString("About_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about.
        /// </summary>
        public static string AppBar_About {
            get {
                return ResourceManager.GetString("AppBar_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add.
        /// </summary>
        public static string AppBar_Add {
            get {
                return ResourceManager.GetString("AppBar_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cancel.
        /// </summary>
        public static string AppBar_Cancel {
            get {
                return ResourceManager.GetString("AppBar_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to check.
        /// </summary>
        public static string AppBar_Check {
            get {
                return ResourceManager.GetString("AppBar_Check", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ok.
        /// </summary>
        public static string AppBar_Ok {
            get {
                return ResourceManager.GetString("AppBar_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to settings.
        /// </summary>
        public static string AppBar_Settings {
            get {
                return ResourceManager.GetString("AppBar_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MY APP PUSHER.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Games.
        /// </summary>
        public static string Category_Games {
            get {
                return ResourceManager.GetString("Category_Games", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTC.
        /// </summary>
        public static string Category_HTC {
            get {
                return ResourceManager.GetString("Category_HTC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft.
        /// </summary>
        public static string Category_Microsoft {
            get {
                return ResourceManager.GetString("Category_Microsoft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nokia.
        /// </summary>
        public static string Category_Nokia {
            get {
                return ResourceManager.GetString("Category_Nokia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Samsung.
        /// </summary>
        public static string Category_Samsung {
            get {
                return ResourceManager.GetString("Category_Samsung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apps.
        /// </summary>
        public static string Category_UserApps {
            get {
                return ResourceManager.GetString("Category_UserApps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An internet connection is not available.\nPlease check your connection and try again..
        /// </summary>
        public static string ErrorMessage_ConnectionNotAvailable {
            get {
                return ResourceManager.GetString("ErrorMessage_ConnectionNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No connection.
        /// </summary>
        public static string ErrorMessage_ConnectionNotAvailable_Caption {
            get {
                return ResourceManager.GetString("ErrorMessage_ConnectionNotAvailable_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot retrieve application information. Please check the application id or try again later..
        /// </summary>
        public static string ErrorMessage_NewApp_CannotGetAppInfo {
            get {
                return ResourceManager.GetString("ErrorMessage_NewApp_CannotGetAppInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server not response..
        /// </summary>
        public static string ErrorMessage_NewApp_CannotGetAppInfo_Caption {
            get {
                return ResourceManager.GetString("ErrorMessage_NewApp_CannotGetAppInfo_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last updated .
        /// </summary>
        public static string Home_LastUpdated {
            get {
                return ResourceManager.GetString("Home_LastUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Home_Unknown {
            get {
                return ResourceManager.GetString("Home_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version .
        /// </summary>
        public static string Home_Version {
            get {
                return ResourceManager.GetString("Home_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for update successful.
        /// </summary>
        public static string Message_CheckUpdateSuccess {
            get {
                return ResourceManager.GetString("Message_CheckUpdateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string Message_CheckUpdateSuccess_Caption {
            get {
                return ResourceManager.GetString("Message_CheckUpdateSuccess_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you deleting item?.
        /// </summary>
        public static string Message_ConfirmDelete {
            get {
                return ResourceManager.GetString("Message_ConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Message_ConfirmDetete_Caption {
            get {
                return ResourceManager.GetString("Message_ConfirmDetete_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App ID.
        /// </summary>
        public static string NewApp_AppID {
            get {
                return ResourceManager.GetString("NewApp_AppID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AppID is not valid.
        /// </summary>
        public static string NewApp_AppIDNotValid {
            get {
                return ResourceManager.GetString("NewApp_AppIDNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string NewApp_Category {
            get {
                return ResourceManager.GetString("NewApp_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applications.
        /// </summary>
        public static string NewApp_Category_Applications {
            get {
                return ResourceManager.GetString("NewApp_Category_Applications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Games.
        /// </summary>
        public static string NewApp_Category_Games {
            get {
                return ResourceManager.GetString("NewApp_Category_Games", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new app.
        /// </summary>
        public static string NewApp_PageTitle {
            get {
                return ResourceManager.GetString("NewApp_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan QR Code.
        /// </summary>
        public static string NewApp_UseQRScanner {
            get {
                return ResourceManager.GetString("NewApp_UseQRScanner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftToRight.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-US.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cancel.
        /// </summary>
        public static string ScanQR_Cancel {
            get {
                return ResourceManager.GetString("ScanQR_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ok.
        /// </summary>
        public static string ScanQR_Ok {
            get {
                return ResourceManager.GetString("ScanQR_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QR Code Scanner.
        /// </summary>
        public static string ScanQR_PageTitle {
            get {
                return ResourceManager.GetString("ScanQR_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result.
        /// </summary>
        public static string ScanQR_Result {
            get {
                return ResourceManager.GetString("ScanQR_Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to settings.
        /// </summary>
        public static string Setting_PageTitle {
            get {
                return ResourceManager.GetString("Setting_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select vendor to check for updates.
        /// </summary>
        public static string Setting_TextDescription {
            get {
                return ResourceManager.GetString("Setting_TextDescription", resourceCulture);
            }
        }
    }
}
