SET NOCOUNT ON;

CREATE TABLE [dbo].[AREA](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[VNNAME] [nvarchar](255) NULL,
	[ENNAME] [nvarchar](255) NULL,
	[BRANCHID] [int] NULL,
	[ENABLE] [bit] NULL,
	[SEQ] [int] NULL,
	[CREATEDDATE] [datetime] NULL,
	[CREATEDUSER] [nvarchar](50) NULL,
	[MODIFIEDDATE] [datetime] NULL,
	[MODIFIEDUSER] [nvarchar](50) NULL,
 CONSTRAINT [PK_AREA] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[BRANCH](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[VNNAME] [nvarchar](255) NULL,
	[ENNAME] [nvarchar](255) NULL,
	[CURRENCYID] [int] NULL,
	[USESERVICEFEE] [bit] NULL,
	[SERVICEFEE] [numeric](19, 2) NULL,
	[USEDISCOUNTONPRODUCT] [bit] NULL,
	[USEKITCHENFUNCTION] [bit] NULL,
	[USEINVENTORY] [bit] NULL,
	[DEPOTID] [int] NULL,
	[ENABLE] [bit] NULL,
	[SEQ] [int] NULL,
	[CREATEDDATE] [datetime] NULL,
	[CREATEDUSER] [nvarchar](50) NULL,
	[MODIFIEDDATE] [datetime] NULL,
	[MODIFIEDUSER] [nvarchar](50) NULL,
 CONSTRAINT [PK_BRANCH] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[BRANCHINFO](
	[ID] [int] NOT NULL,
	[COMPANYCODE] [nvarchar](255) NULL,
	[COMPANYNAME] [nvarchar](510) NULL,
	[PHONE] [nvarchar](50) NULL,
	[FAX] [nvarchar](50) NULL,
	[EMAIL] [nvarchar](255) NULL,
	[TAXCODE] [nvarchar](50) NULL,
	[ADDRESS] [nvarchar](510) NULL,
	[INFO1] [nvarchar](510) NULL,
	[INFO2] [nvarchar](510) NULL,
	[INFO3] [nvarchar](510) NULL,
	[INFO4] [nvarchar](510) NULL,
	[INFO5] [nvarchar](510) NULL,
	[INFO6] [nvarchar](510) NULL,
	[INFO7] [nvarchar](510) NULL,
	[INFO8] [nvarchar](510) NULL,
	[INFO9] [nvarchar](510) NULL,
	[INFO10] [nvarchar](510) NULL,
 CONSTRAINT [PK_BRANCHINFO] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[BRANCHTAX](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[BRANCHID] [int] NULL,
	[TAXID] [int] NULL,
 CONSTRAINT [PK_BRANCHTAX] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[BRANDINGTEXT](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[BRANCHID] [int] NULL,
	[KEY] [nvarchar](100) NULL,
	[VNVALUE] [nvarchar](1000) NULL,
	[ENVALUE] [nvarchar](1000) NULL,
 CONSTRAINT [PK_BRANDINGTEXT] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[CATEGORY](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[CATEGORYCODE] [nvarchar](50) NULL,
	[VNNAME] [nvarchar](255) NULL,
	[ENNAME] [nvarchar](255) NULL,
	[VNDESCRIPTION] [nvarchar](255) NULL,
	[ENDESCTIPTION] [nvarchar](255) NULL,
	[BRANCHID] [int] NULL,
	[ENABLE] [bit] NULL,
	[SEQ] [int] NULL,
	[CREATEDDATE] [datetime] NULL,
	[CREATEDUSER] [nvarchar](50) NULL,
	[MODIFIEDDATE] [datetime] NULL,
	[MODIFIEDUSER] [nvarchar](50) NULL,
 CONSTRAINT [PK_CATEGORY] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[CURRENCY](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[NAME] [nvarchar](50) NOT NULL,
	[DESCRIPTION] [nvarchar](255) NOT NULL,
	[EXCHANGE] [numeric](19, 2) NULL,
	[ENABLE] [bit] NULL,
	[SEQ] [int] NULL,
	[CREATEDDATE] [datetime] NULL,
	[CREATEDUSER] [nvarchar](50) NULL,
	[MODIFIEDDATE] [datetime] NULL,
	[MODIFIEDUSER] [nvarchar](50) NULL,
 CONSTRAINT [PK_CURRENCY] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[CUSTOMER](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[CUSTOMERCODE] [nvarchar](50) NOT NULL,
	[CUSTOMERNAME] [nvarchar](255) NULL,
	[CELLPHONE] [nvarchar](50) NULL,
	[ADDRESS] [nvarchar](510) NULL,
	[DOB] [datetime] NULL,
	[BRANCHID] [int] NULL,
	[ENABLE] [bit] NULL,
	[SEQ] [int] NULL,
	[CREATEDDATE] [datetime] NULL,
	[CREATEDUSER] [nvarchar](50) NULL,
	[MODIFIEDDATE] [datetime] NULL,
	[MODIFIEDUSER] [nvarchar](50) NULL,
 CONSTRAINT [PK_CUSTOMER] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[DELIVERYITEM](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[DELIVERYNOTEID] [bigint] NULL,
	[ITEMID] [bigint] NULL,
	[QUANTITY] [numeric](10, 2) NULL,
	[UNITPRICE] [numeric](19, 2) NULL,
	[AMOUNT] [numeric](19, 2) NULL,
	[CREATEDDATE] [datetime] NULL,
	[CREATEDUSER] [nvarchar](50) NULL,
	[MODIFIEDDATE] [datetime] NULL,
	[MODIFIEDUSER] [nvarchar](50) NULL,
 CONSTRAINT [PK_DELIVERYITEM] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[DELIVERYNOTE](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[DEPOTID] [int] NULL,
	[DELIVERYNUMBER] [nvarchar](50) NULL,
	[DELIVERYDATE] [datetime] NULL,
	[DELIVERYTYPEID] [tinyint] NULL,
	[COMMENT] [nvarchar](255) NULL,
	[CUSTOMERID] [bigint] NULL,
	[TODEPOTID] [bigint] NULL,
	[DOCUMENTID] [bigint] NULL,
	[RECEIVER] [nvarchar](255) NULL,
	[SHIPADDRESS] [nvarchar](1000) NULL,
	[SHIPCONTACT] [nvarchar](1000) NULL,
	[TOTALAMOUNT] [numeric](19, 2) NULL,
	[CURRENCY] [nvarchar](50) NULL,
	[CREATEDDATE] [datetime] NULL,
	[CREATEDUSER] [nvarchar](50) NULL,
	[MODIFIEDDATE] [datetime] NULL,
	[MODIFIEDUSER] [nvarchar](50) NULL,
 CONSTRAINT [PK_DELIVERYNOTE] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[DELIVERYTYPE](
	[ID] [tinyint] IDENTITY(1,1) NOT NULL,
	[VNNAME] [nvarchar](255) NULL,
	[ENNAME] [nvarchar](255) NULL,
	[USEIMPORTPRICE] [bit] NULL,
	[CREATEDDATE] [datetime] NULL,
	[CREATEDUSER] [nvarchar](50) NULL,
	[MODIFIEDDATE] [datetime] NULL,
	[MODIFIEDUSER] [nvarchar](50) NULL,
 CONSTRAINT [PK_DELIVERYTYPE] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[DEPOT](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[DEPOTCODE] [nvarchar](50) NULL,
	[DEPOTNAME] [nvarchar](1000) NULL,
	[PHONE] [nvarchar](50) NULL,
	[FAX] [nvarchar](50) NULL,
	[EMAIL] [nvarchar](255) NULL,
	[ADDRESS] [nvarchar](510) NULL,
	[ENABLE] [bit] NULL,
	[SEQ] [int] NULL,
	[CREATEDDATE] [datetime] NULL,
	[CREATEDUSER] [nvarchar](50) NULL,
	[MODIFIEDDATE] [datetime] NULL,
	[MODIFIEDUSER] [nvarchar](50) NULL,
 CONSTRAINT [PK_DEPOT] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[DOCUMENT](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[FILENAME] [nchar](10) NULL,
	[FILETYPE] [nvarchar](50) NULL,
	[DOCUMENTTYPE] [varchar](10) NULL,
	[CREATEDDATE] [datetime] NULL,
	[CREATEDUSER] [nvarchar](50) NULL,
	[MODIFIEDDATE] [datetime] NULL,
	[MODIFIEDUSER] [nvarchar](50) NULL,
 CONSTRAINT [PK_DOCUMENT] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[ERRORMESSAGE](
	[ID] [int] NOT NULL,
	[MESSAGEID] [int] NULL,
	[BRANCHID] [int] NULL,
	[VNMESSAGE] [nvarchar](1000) NULL,
	[ENMESSAGE] [nvarchar](1000) NULL,
 CONSTRAINT [PK_ERRORMESSAGE] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[INVENTORY](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[DEPOTID] [int] NULL,
	[ITEMID] [bigint] NULL,
	[QUANTITY] [numeric](10, 2) NULL,
	[CREATEDDATE] [datetime] NULL,
	[CREATEDUSER] [nvarchar](50) NULL,
	[MODIFIEDDATE] [datetime] NULL,
	[MODIFIEDUSER] [nvarchar](50) NULL,
 CONSTRAINT [PK_INVENTORY] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[INVOICE](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[BRANCHID] [int] NULL,
	[INVOICENUMBER] [nvarchar](50) NULL,
	[INVOICEDATE] [datetime] NULL,
	[COMMENT] [nvarchar](255) NULL,
	[CUSTOMERID] [int] NULL,
	[CUSTOMERNAME] [nvarchar](255) NULL,
	[CELLPHONE] [nvarchar](50) NULL,
	[ADDRESS] [nvarchar](510) NULL,
	[DOB] [datetime] NULL,
	[SERVICEFEE] [numeric](19, 2) NULL,
	[OTHERFEE] [numeric](19, 2) NULL,
	[OTHERFEEDESCRIPTION] [nvarchar](255) NULL,
	[TAXINFO] [nvarchar](255) NULL,
	[CURRENCYID] [nvarchar](50) NULL,
	[PAYMENTMETHOD] [tinyint] NULL,
	[TAXMOUNT] [numeric](19, 2) NULL,
	[DISCOUNTADMOUNT] [numeric](19, 2) NULL,
	[INVOICEAMOUNT] [numeric](19, 2) NULL,
	[CREATEDDATE] [datetime] NULL,
	[CREATEDUSER] [nvarchar](50) NULL,
	[MODIFIEDDATE] [datetime] NULL,
	[MODIFIEDUSER] [nvarchar](50) NULL,
 CONSTRAINT [PK_INVOICE] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[INVOICEDETAIL](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[INVOICETABLEID] [bigint] NULL,
	[PRODUCTID] [int] NULL,
	[QUANTITY] [numeric](10, 2) NULL,
	[UNITPRICE] [numeric](19, 2) NULL,
	[DISCOUNT] [numeric](19, 2) NULL,
	[DISCOUNTTYPE] [tinyint] NULL,
	[DISCOUNTCODE] [nvarchar](50) NULL,
	[DISCOUNTCOMMENT] [nvarchar](255) NULL,
	[DISCOUNTAMOUNT] [numeric](19, 2) NULL,
	[AMOUNT] [numeric](19, 2) NULL,
	[CREATEDDATE] [datetime] NULL,
	[CREATEDUSER] [nvarchar](50) NULL,
	[MODIFIEDDATE] [datetime] NULL,
	[MODIFIEDUSER] [nvarchar](50) NULL,
 CONSTRAINT [PK_INVOICEDETAIL] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[INVOICEDISCOUNT](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[INVOICEID] [bigint] NULL,
	[DISCOUNT] [numeric](19, 2) NULL,
	[DISCOUNTTYPE] [tinyint] NULL,
	[DISCOUNTCODE] [nvarchar](50) NULL,
	[DISCOUNTCOMMENT] [nvarchar](255) NULL,
 CONSTRAINT [PK_INVOICEDISCOUNT] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[INVOICETABLE](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[INVOICEID] [bigint] NULL,
	[TABLEID] [int] NULL,
	[DISCOUNT] [numeric](19, 2) NULL,
	[DISCOUNTTYPE] [tinyint] NULL,
	[DISCOUNTCODE] [nvarchar](50) NULL,
	[DISCOUNTCOMMENT] [nvarchar](255) NULL,
	[SERVICEFEE] [numeric](19, 2) NULL,
	[OTHERFEE] [numeric](19, 2) NULL,
	[OTHERFEEDESCRIPTION] [nvarchar](255) NULL,
	[DETAILAMOUNT] [numeric](19, 2) NULL,
	[DISCOUNTAMOUNT] [numeric](19, 2) NULL,
	[AMOUNT] [numeric](19, 2) NULL,
	[CREATEDDATE] [datetime] NULL,
	[CREATEDUSER] [nvarchar](50) NULL,
	[MODIFIEDDATE] [datetime] NULL,
	[MODIFIEDUSER] [nvarchar](50) NULL,
 CONSTRAINT [PK_INVOICETABLE] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[ITEM](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[ITEMCODE] [nvarchar](50) NULL,
	[VNNAME] [nvarchar](1000) NULL,
	[ENNAME] [nvarchar](1000) NULL,
	[VNDESCRIPTION] [nvarchar](1000) NULL,
	[ENDESCRIPTION] [nvarchar](1000) NULL,
	[UNITID] [int] NULL,
	[CATEGORYID] [int] NULL,
	[ISINVENTORY] [bit] NULL,
	[MINQUANTITY] [numeric](10, 2) NULL,
	[ENABLE] [bit] NULL,
	[SEQ] [int] NULL,
	[CREATEDDATE] [datetime] NULL,
	[CREATEDUSER] [nvarchar](50) NULL,
	[MODIFIEDDATE] [datetime] NULL,
	[MODIFIEDUSER] [nvarchar](50) NULL,
 CONSTRAINT [PK_ITEM] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[ORDER](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[BRANCHID] [int] NULL,
	[ORDERNUMBER] [nvarchar](50) NULL,
	[COMMENT] [nvarchar](255) NULL,
	[CUSTOMERID] [int] NULL,
	[CUSTOMERNAME] [nvarchar](255) NULL,
	[CELLPHONE] [nvarchar](50) NULL,
	[ADDRESS] [nvarchar](510) NULL,
	[DOB] [datetime] NULL,
	[OTHERFEE] [numeric](19, 2) NULL,
	[OTHERFEEDESCRIPTION] [nvarchar](255) NULL,
	[ORDERPROGRESSSTATUS] [tinyint] NULL,
	[CREATEDDATE] [datetime] NULL,
	[CREATEDUSER] [nvarchar](50) NULL,
	[MODIFIEDDATE] [datetime] NULL,
	[MODIFIEDUSER] [nvarchar](50) NULL,
 CONSTRAINT [PK_ORDER] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[ORDERDETAIL](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[ORDERTABLEID] [bigint] NULL,
	[PRODUCTID] [int] NULL,
	[QUANTIY] [numeric](10, 2) NULL,
	[COMMENT] [nvarchar](255) NULL,
	[DISCOUNT] [numeric](19, 2) NULL,
	[DISCOUNTTYPE] [tinyint] NULL,
	[DISCOUNTCODE] [nvarchar](50) NULL,
	[DISCOUNTCOMMENT] [nvarchar](255) NULL,
	[KITCHENCOMMENT] [nvarchar](255) NULL,
	[ORDERSTATUS] [tinyint] NULL,
	[CREATEDDATE] [datetime] NULL,
	[CREATEDUSER] [nvarchar](50) NULL,
	[MODIFIEDDATE] [datetime] NULL,
	[MODIFIEDUSER] [nvarchar](50) NULL,
 CONSTRAINT [PK_ORDERDETAIL] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[ORDERDISCOUNT](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[ORDERID] [bigint] NULL,
	[DISCOUNT] [numeric](19, 2) NULL,
	[DISCOUNTTYPE] [tinyint] NULL,
	[DISCOUNTCODE] [nvarchar](50) NULL,
	[DISCOUNTCOMMENT] [nvarchar](255) NULL,
 CONSTRAINT [PK_ORDERDISCOUNT] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[ORDERTABLE](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[ORDERID] [bigint] NULL,
	[TABLEID] [int] NULL,
	[DISCOUNT] [numeric](19, 2) NULL,
	[DISCOUNTTYPE] [tinyint] NULL,
	[DISCOUNTCODE] [nvarchar](50) NULL,
	[DISCOUNTCOMMENT] [nvarchar](255) NULL,
	[USESERVICEFEE] [bit] NULL,
	[OTHERFEE] [numeric](19, 2) NULL,
	[OTHERFEEDESCRIPTION] [nvarchar](255) NULL,
	[CREATEDDATE] [datetime] NULL,
	[CREATEDUSER] [nvarchar](50) NULL,
	[MODIFIEDDATE] [datetime] NULL,
	[MODIFIEDUSER] [nvarchar](50) NULL,
 CONSTRAINT [PK_ORDERTABLE] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[PAGE](
	[ID] [int] NOT NULL,
	[VNTITLE] [nvarchar](255) NULL,
	[ENTITLE] [nvarchar](255) NULL,
	[VNDESCRIPTION] [nvarchar](500) NULL,
	[ENDESCRIPTION] [nvarchar](500) NULL,
	[TYPE] [tinyint] NULL,
	[AREA] [nvarchar](50) NULL,
	[CONTROLLER] [nvarchar](50) NULL,
	[ACTION] [nvarchar](50) NULL,
	[ENABLE] [bit] NULL,
 CONSTRAINT [PK_PAGE] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[PAGELABEL](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[LABELID] [nvarchar](50) NULL,
	[BRANCHID] [int] NULL,
	[PAGEID] [int] NULL,
	[VNTEXT] [nvarchar](500) NULL,
	[ENTEXT] [nvarchar](500) NULL,
 CONSTRAINT [PK_PAGELABEL] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[PAGEMENU](
	[ID] [int] NOT NULL,
	[GROUPNAME] [nvarchar](50) NULL,
	[PARENTID] [int] NULL,
	[PAGEID] [int] NULL,
	[SEQ] [int] NULL,
 CONSTRAINT [PK_PAGEMENU] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[PAYMENTVOUCHER](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[DEPOTID] [int] NULL,
	[PAYMENTNUMBER] [nvarchar](50) NULL,
	[PAYMENTDATE] [date] NULL,
	[VENDORID] [bigint] NULL,
	[TODEPOTID] [int] NULL,
	[RECEIVER] [nvarchar](255) NULL,
	[TOTALAMOUNT] [numeric](19, 2) NULL,
	[INWORDS] [nvarchar](510) NULL,
	[DESCRIPTION] [nvarchar](510) NULL,
	[DOCUMENTID] [bigint] NULL,
	[ENABLE] [bit] NULL,
	[CREATEDDATE] [datetime] NULL,
	[CREATEDUSER] [nvarchar](50) NULL,
	[MODIFIEDDATE] [datetime] NULL,
	[MODIFIEDUSER] [nvarchar](50) NULL,
 CONSTRAINT [PK_PAYMENTVOUCHER_1] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[PRODUCT](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[PRODUCTCODE] [nvarchar](50) NULL,
	[VNNAME] [nvarchar](1000) NULL,
	[ENNAME] [nvarchar](1000) NULL,
	[VNDESCRIPTION] [nvarchar](1000) NULL,
	[ENDESCRIPTION] [nvarchar](1000) NULL,
	[UNITID] [int] NULL,
	[CATEGORYID] [int] NULL,
	[UNITPRICE] [numeric](19, 2) NULL,
	[ENBLE] [bit] NULL,
	[SEQ] [int] NULL,
	[CREATEDDATE] [datetime] NULL,
	[CREATEDUSER] [nvarchar](50) NULL,
	[MODIFIEDDATE] [datetime] NULL,
	[MODIFIEDUSER] [nvarchar](50) NULL,
 CONSTRAINT [PK_PRODUCT] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[PRODUCTPRICEHISTORY](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[PRODUCTID] [int] NULL,
	[OLDUNITPRICE] [numeric](19, 2) NULL,
	[NEWUNITPRICE] [numeric](19, 2) NULL,
	[CREATEDDATE] [datetime] NULL,
	[CREATEDUSER] [nvarchar](50) NULL,
 CONSTRAINT [PK_PRODUCTPRICEHISTORY] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[RECEIPTITEM](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[RECEIPTNOTEID] [bigint] NULL,
	[ITEMID] [bigint] NULL,
	[QUANTITY] [numeric](10, 2) NULL,
	[UNITPRICE] [numeric](19, 2) NULL,
	[AMOUNT] [numeric](19, 2) NULL,
	[CREATEDDATE] [datetime] NULL,
	[CREATEDUSER] [nvarchar](50) NULL,
	[MODIFIEDDATE] [datetime] NULL,
	[MODIFIEDUSER] [nvarchar](50) NULL,
 CONSTRAINT [PK_RECEIPTITEM] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[RECEIPTNOTE](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[DEPOTID] [int] NULL,
	[RECEIPTNUMBER] [nvarchar](50) NULL,
	[RECEIPTDATE] [datetime] NULL,
	[VENDORID] [bigint] NULL,
	[FROMDEPOTID] [int] NULL,
	[SHIPPER] [nvarchar](255) NULL,
	[COMMENT] [nvarchar](255) NULL,
	[DOCUMENTID] [bigint] NULL,
	[TOTALAMOUNT] [numeric](19, 2) NULL,
	[CURRENCY] [nvarchar](50) NULL,
	[CREATEDDATE] [datetime] NULL,
	[CREATEDUSER] [nvarchar](50) NULL,
	[MODIFIEDDATE] [datetime] NULL,
	[MODIFIEDUSER] [nvarchar](50) NULL,
 CONSTRAINT [PK_RECEIPTNOTE] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[RECEIPTVOUCHER](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[DEPOTID] [int] NULL,
	[RECEIPTNUMBER] [nvarchar](50) NULL,
	[RECEIPTDATE] [date] NULL,
	[CUSTOMERID] [int] NULL,
	[FROMDEPOTID] [int] NULL,
	[PAYER] [nvarchar](255) NULL,
	[TOTALAMOUNT] [numeric](19, 2) NULL,
	[INWORDS] [nvarchar](510) NULL,
	[DESCRIPTION] [nvarchar](510) NULL,
	[DOCUMENTID] [bigint] NULL,
	[ENABLE] [bit] NULL,
	[CREATEDDATE] [datetime] NULL,
	[CREATEDUSER] [nvarchar](50) NULL,
	[MODIFIEDDATE] [datetime] NULL,
	[MODIFIEDUSER] [nvarchar](50) NULL,
 CONSTRAINT [PK_RECEIPTVOUCHER] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[REJECT](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[BRANCHID] [int] NULL,
	[PRODUCTID] [int] NULL,
	[QUANTITY] [numeric](10, 2) NULL,
	[ORDERCOMMENT] [nvarchar](255) NULL,
	[KITCHENCOMMENT] [nvarchar](255) NULL,
	[CREATEDDATE] [datetime] NULL,
	[CREATEDUSER] [nvarchar](50) NULL,
 CONSTRAINT [PK_REJECT] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[ROLE](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[VNNAME] [nvarchar](510) NOT NULL,
	[ENNAME] [nvarchar](510) NULL,
	[BRANCHID] [int] NULL,
	[ENABLE] [bit] NULL,
	[SEQ] [int] NULL,
	[CREATEDDATE] [datetime] NULL,
	[CREATEDUSER] [nvarchar](50) NULL,
	[MODIFIEDDATE] [datetime] NULL,
	[MODIFIEDUSER] [nvarchar](50) NULL,
 CONSTRAINT [PK_ROLE] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[ROLEPERMISSION](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[ROLEID] [int] NOT NULL,
	[PAGEID] [int] NOT NULL,
	[CREATEDDATE] [datetime] NULL,
	[CREATEDUSER] [nvarchar](50) NULL,
	[MODIFIEDDATE] [datetime] NULL,
	[MODIFIEDUSER] [nvarchar](50) NULL,
 CONSTRAINT [PK_ROLEPERMISSION] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[SQLSTATEMENT](
	[NAME] [varchar](255) NOT NULL,
	[QUERYSTRING] [nvarchar](1000) NULL,
	[DESCRIPTION] [nvarchar](510) NULL,
 CONSTRAINT [PK_SQLSTATEMENT] PRIMARY KEY CLUSTERED 
(
	[NAME] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[SYSTEMINFORMATION](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[NAME] [nvarchar](255) NOT NULL,
	[DESCRIPTION] [nvarchar](255) NOT NULL,
	[VALUE] [nvarchar](510) NULL,
	[TYPE] [tinyint] NULL,
 CONSTRAINT [PK_SYSTEMINFORMATION] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[TABLE](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[VNNAME] [nvarchar](255) NULL,
	[ENNAME] [nvarchar](255) NULL,
	[AREAID] [int] NULL,
	[ENABE] [bit] NULL,
	[SEQ] [int] NULL,
	[CREATEDDATE] [datetime] NULL,
	[CREATEDUSER] [nvarchar](50) NULL,
	[MODIFIEDDATE] [datetime] NULL,
	[MODIFIEDUSER] [nvarchar](50) NULL,
 CONSTRAINT [PK_TABLE] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[TAX](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[NAME] [nvarchar](10) NOT NULL,
	[DESCRIPTION] [nvarchar](255) NULL,
	[VALUE] [numeric](5, 2) NULL,
	[ENABLE] [bit] NULL,
	[SEQ] [int] NULL,
	[CREATEDDATE] [datetime] NULL,
	[CREATEDUSER] [nvarchar](50) NULL,
	[MODIFIEDDATE] [datetime] NULL,
	[MODIFIEDUSER] [nvarchar](50) NULL,
 CONSTRAINT [PK_TAX] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[UNIT](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[BRANCHID] [int] NULL,
	[VNNAME] [nvarchar](255) NULL,
	[ENNAME] [nvarchar](255) NULL,
	[ENABLE] [bit] NULL,
	[SEQ] [int] NULL,
	[CREATEDDATE] [datetime] NULL,
	[CREATEDUSER] [nvarchar](50) NULL,
	[MODIFIEDDATE] [datetime] NULL,
	[MODIFIEDUSER] [nvarchar](50) NULL,
 CONSTRAINT [PK_UNIT] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[UPLOADEDFILE](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[CATEGORY] [tinyint] NULL,
	[PHYSICALPATH] [nvarchar](100) NULL,
	[CREATEDDATE] [datetime] NULL,
	[CREATEDUSER] [nvarchar](50) NULL,
 CONSTRAINT [PK_UPLOADEDFILE] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[USER](
	[ID] [uniqueidentifier] NOT NULL,
	[USERNAME] [nvarchar](255) NOT NULL,
	[PASSWORD] [nvarchar](1000) NOT NULL,
	[FIRSTNAME] [nvarchar](255) NULL,
	[LASTNAME] [nvarchar](255) NULL,
	[CELLPHONE] [nvarchar](50) NULL,
	[EMAIL] [nvarchar](255) NULL,
	[ADDRESS] [nvarchar](255) NULL,
	[LASTLOGINDATE] [datetime] NULL,
	[ISSYSTEMADMIN] [bit] NULL,
	[USESYSTEMCONFIG] [bit] NULL,
	[ISLOCKEDOUT] [bit] NULL,
	[LASTLOCKEDOUTDATE] [datetime] NULL,
	[FAILEDPASSWORDATTEMPTCOUNT] [int] NULL,
	[CREATEDDATE] [datetime] NULL,
	[CREATEDUSER] [nvarchar](50) NULL,
	[MODIFIEDDATE] [datetime] NULL,
	[MODIFIEDUSER] [nvarchar](50) NULL,
 CONSTRAINT [PK_USER] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[USERBRANCH](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[USERID] [uniqueidentifier] NULL,
	[BRANCHID] [int] NULL,
 CONSTRAINT [PK_USERBRANCH] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[USERCONFIG](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[USERID] [uniqueidentifier] NULL,
	[BRANCHID] [int] NULL,
	[ISSUSPENDED] [bit] NULL,
	[DEFAULTAREA] [int] NULL,
	[LISTTABLEHEIGHT] [numeric](19, 2) NULL,
	[PAGESIZE] [int] NULL,
	[THEME] [nvarchar](50) NULL,
	[CREATEDDATE] [datetime] NULL,
	[CREATEDUSER] [nvarchar](50) NULL,
	[MODIFIEDDATE] [datetime] NULL,
	[MODIFIEDUSER] [nvarchar](50) NULL,
 CONSTRAINT [PK_USERCONFIG] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[USERINROLE](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[USERID] [uniqueidentifier] NULL,
	[ROLEID] [int] NOT NULL,
 CONSTRAINT [PK_USERINROLE] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[VENDOR](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[VENDORNUMBER] [nvarchar](50) NULL,
	[VENDORNAME] [nvarchar](1000) NULL,
	[PHONE] [nvarchar](50) NULL,
	[FAX] [nvarchar](50) NULL,
	[EMAIL] [nvarchar](255) NULL,
	[TAXCODE] [nvarchar](50) NULL,
	[ADDRESS] [nvarchar](510) NULL,
	[ENABLE] [bit] NULL,
	[SEQ] [int] NULL,
	[CREATEDDATE] [datetime] NULL,
	[CREATEDUSER] [nvarchar](50) NULL,
	[MODIFIEDDATE] [datetime] NULL,
	[MODIFIEDUSER] [nvarchar](50) NULL,
 CONSTRAINT [PK_VENDOR] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO


/*************************************************************************************/
/*************************************************************************************/
/*************************************************************************************/
/*************************************************************************************/

CREATE TRIGGER [dbo].[trigger_ProductPriceLog] ON [dbo].[PRODUCT] FOR UPDATE
AS
    SET NOCOUNT ON
    IF UPDATE(UNITPRICE)
    BEGIN
        DECLARE @oldPrice NUMERIC(12, 2);
        SELECT @oldPrice = UNITPRICE FROM deleted;

        IF EXISTS ( SELECT TOP 1 1 FROM inserted WHERE UNITPRICE <> @oldPrice )
        BEGIN
            INSERT INTO dbo.ProductPriceHistory (PRODUCTID, OLDUNITPRICE, NEWUNITPRICE, CREATEDDATE, CREATEDUSER )
            SELECT ID, @oldPrice, UNITPRICE, MODIFIEDDATE, MODIFIEDUSER FROM inserted
        END
    END
GO