SET NOCOUNT ON;

DECLARE @str VARCHAR(2000) = '';
        
DECLARE cur CURSOR FAST_FORWARD READ_ONLY FOR
SELECT 'ALTER TABLE [dbo].[' + OBJECT_NAME(parent_object_id) + '] DROP CONSTRAINT [' + OBJECT_NAME(constraint_object_id) + ']'
FROM sys.foreign_key_columns
WHERE OBJECT_NAME(parent_object_id) IN ('TABLE', 'INVOICE', 'TAX', 'INVOICEDETAIL', 'INVOICETABLE', 'ORDER', 'ORDERTABLE', 
										'PAGE', 'PAGELABEL', 'REJECT', 'ORDERDETAIL', 'ROLE', 'ORDERDISCOUNT', 'PAGEMENU', 
										'ROLEPERMISSION', 'USER', 'BRANDINGTEXT', 'UPLOADEDFILE', 'USERBRANCH', 'DEPOT', 
										'USERCONFIG', 'ITEM', 'USERINROLE', 'VENDOR', 'DELIVERYITEM', 'DELIVERYNOTE', 'DELIVERYTYPE', 
										'INVENTORY', 'RECEIPTNOTE', 'RECEIPTITEM', 'PAYMENTVOUCHER', 'RECEIPTVOUCHER', 'DOCUMENT', 
										'SQLSTATEMENT', 'BRANCHINFO', 'BRANCHTAX', 'ERRORMESSAGE', 'UNIT', 'AREA', 'INVOICEDISCOUNT', 
										'BRANCH', 'PRODUCT', 'CATEGORY', 'CURRENCY', 'PRODUCTPRICEHISTORY', 'CUSTOMER', 'SYSTEMINFORMATION', 'USERSINROLE')
OPEN cur
FETCH NEXT FROM cur INTO @str
WHILE @@FETCH_STATUS = 0
BEGIN
    EXECUTE(@str);

FETCH NEXT FROM cur INTO @str      
END
CLOSE cur
DEALLOCATE cur

DECLARE cur CURSOR FAST_FORWARD READ_ONLY FOR
SELECT 'DROP TABLE [dbo].[' + name + ']'
FROM sys.objects
WHERE type = 'U'
    AND name IN (   'TABLE', 'INVOICE', 'TAX', 'INVOICEDETAIL', 'INVOICETABLE', 'ORDER', 'ORDERTABLE', 
					'PAGE', 'PAGELABEL', 'REJECT', 'ORDERDETAIL', 'ROLE', 'ORDERDISCOUNT', 'PAGEMENU', 
					'ROLEPERMISSION', 'USER', 'BRANDINGTEXT', 'UPLOADEDFILE', 'USERBRANCH', 'DEPOT', 
					'USERCONFIG', 'ITEM', 'USERINROLE', 'VENDOR', 'DELIVERYITEM', 'DELIVERYNOTE', 'DELIVERYTYPE', 
					'INVENTORY', 'RECEIPTNOTE', 'RECEIPTITEM', 'PAYMENTVOUCHER', 'RECEIPTVOUCHER', 'DOCUMENT', 
					'SQLSTATEMENT', 'BRANCHINFO', 'BRANCHTAX', 'ERRORMESSAGE', 'UNIT', 'AREA', 'INVOICEDISCOUNT', 
					'BRANCH', 'PRODUCT', 'CATEGORY', 'CURRENCY', 'PRODUCTPRICEHISTORY', 'CUSTOMER', 'SYSTEMINFORMATION', 'USERSINROLE')
OPEN cur
FETCH NEXT FROM cur INTO @str
WHILE @@FETCH_STATUS = 0
BEGIN
    EXECUTE(@str)     

FETCH NEXT FROM cur INTO @str      
END
CLOSE cur
DEALLOCATE cur